### ISSUE TITLE
Cannot parse integer from empty string error

### ISSUE THREAD

**Issue by timmerk** [lefth/subtitle-adjust#1]
./subtitle-adjust --offset -68 --offset-start 18:11:18 subs.srt
Error: Error processing subtitles

Caused by:
    cannot parse integer from empty string

[subs.txt](https://github.com/lefth/subtitle-adjust/files/7944242/subs.txt)
Note, I renamed the filename to .txt instead of .srt since Github wouldn't let me upload a .srt file.
The file has Unix style line endings, and running subtitle-adjust on a M1 Silicon Macbook under Mac OS 12.

**Comment by timmerk** [comment]
The problem seems to be timestamps with ",000". Once I replaced those with ",001", the program ran and exported a new srt file.

**Comment by lefth** [comment]
Thanks @timmerk! I just pushed the fix as commit 545fc4b5f8a9584e193a709d5acd2be0ea9accd3.
